import re
from collections import Counter
from collections.abc import Mapping
from dataclasses import dataclass
from os import environ
from pathlib import Path


@dataclass(frozen=True, slots=True)
class Settings:
    yonote_base_url: str
    yonote_api_key: str
    github_webhook_secret: str
    yonote_webhook_path_secret: str
    board_id: str
    status_property_id: str
    assignee_property_id: str
    task_id_property_id: str
    branch_property_id: str
    pr_property_id: str
    in_progress_status_id: str
    review_status_id: str
    done_status_id: str
    assignee_id: str
    repository: str
    base_branch: str
    poll_interval: int
    host: str
    port: int
    database_path: Path
    git_dir: Path
    ssh_key: Path
    known_hosts: Path

    @classmethod
    def from_env(cls) -> "Settings":
        return cls.from_mapping(environ)

    @classmethod
    def from_mapping(cls, values: Mapping[str, str]) -> "Settings":
        def required(name: str) -> str:
            value = values.get(name, "").strip()
            if not value:
                raise ValueError(f"{name} must be set and non-empty")
            return value

        def credential(name: str) -> str:
            value = required(name)
            if value.casefold() == "replace-me":
                raise ValueError(f"{name} must not use a placeholder")
            if len(value) < 32:
                raise ValueError(f"{name} must contain at least 32 characters")
            return value

        def generated_secret(name: str) -> str:
            value = credential(name)
            if re.fullmatch(r"[A-Za-z0-9_-]{64,}", value) is None:
                raise ValueError(
                    f"{name} must be generated by secrets.token_urlsafe(48)"
                )
            counts = Counter(value)
            if len(counts) < 16 or max(counts.values()) > len(value) // 4:
                raise ValueError(f"{name} has a predictably imbalanced character mix")
            alphabets = (
                "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_",
                "abcdefghijklmnopqrstuvwxyz",
                "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                "0123456789",
            )
            lowered = value.casefold()
            for alphabet in alphabets:
                for sequence in (alphabet, alphabet[::-1]):
                    for start in range(len(sequence) - 7):
                        if sequence[start : start + 8].casefold() in lowered:
                            raise ValueError(f"{name} must not contain predictable sequences")
            for pattern_length in range(1, len(value) // 2 + 1):
                if len(value) % pattern_length == 0:
                    pattern = value[:pattern_length]
                    if pattern * (len(value) // pattern_length) == value:
                        raise ValueError(f"{name} must not repeat a predictable pattern")
            return value

        def positive_int(name: str, default: str) -> int:
            value = int(values.get(name, default))
            if value <= 0:
                raise ValueError(f"{name} must be greater than zero")
            return value

        def port(name: str, default: str) -> int:
            value = int(values.get(name, default))
            if not 1 <= value <= 65535:
                raise ValueError(f"{name} must be between 1 and 65535")
            return value

        yonote_api_key = credential("YONOTE_API_KEY")
        github_webhook_secret = generated_secret("GITHUB_WEBHOOK_SECRET")
        yonote_webhook_path_secret = generated_secret("YONOTE_WEBHOOK_PATH_SECRET")
        if len({yonote_api_key, github_webhook_secret, yonote_webhook_path_secret}) != 3:
            raise ValueError("Secrets must be distinct")

        return cls(
            yonote_base_url=required("YONOTE_BASE_URL"),
            yonote_api_key=yonote_api_key,
            github_webhook_secret=github_webhook_secret,
            yonote_webhook_path_secret=yonote_webhook_path_secret,
            board_id=values.get(
                "YONOTE_BOARD_ID", "f2da8f12-a8de-4070-9d9a-692f0bdbd1fe"
            ),
            status_property_id=values.get(
                "YONOTE_STATUS_PROPERTY_ID", "dec722a5-72b4-442f-9b6f-e706a9bffade"
            ),
            assignee_property_id=values.get(
                "YONOTE_ASSIGNEE_PROPERTY_ID", "1cce00e1-17b8-4f4b-8339-21fd6e5ee371"
            ),
            task_id_property_id=values.get(
                "YONOTE_TASK_ID_PROPERTY_ID", "2add1be5-7a2d-5814-979b-87f505f59a1c"
            ),
            branch_property_id=values.get(
                "YONOTE_BRANCH_PROPERTY_ID", "1aa299f6-4e6b-5b8d-bfd6-e27a819970f1"
            ),
            pr_property_id=values.get(
                "YONOTE_PR_PROPERTY_ID", "70fb47a1-8d3d-5576-b496-d959e54be8a1"
            ),
            in_progress_status_id=values.get(
                "YONOTE_IN_PROGRESS_STATUS_ID", "34dff37f-9f7d-4ca0-ac16-0c58d3b442d4"
            ),
            review_status_id=values.get(
                "YONOTE_REVIEW_STATUS_ID", "349cbc8f-daf0-4687-a7fe-391b092b23d9"
            ),
            done_status_id=values.get(
                "YONOTE_DONE_STATUS_ID", "035b5c5f-f315-4c8a-9c44-6c7776852d9b"
            ),
            assignee_id=values.get(
                "YONOTE_ASSIGNEE_ID", "632a8b92-3611-477b-b6d6-b5a0df87e57e"
            ),
            repository=values.get("GITHUB_REPOSITORY", "Joskmo/menti-daniil"),
            base_branch=values.get("GITHUB_BASE_BRANCH", "main"),
            poll_interval=positive_int("POLL_INTERVAL_SECONDS", "15"),
            host=values.get("HOST", "0.0.0.0"),
            port=port("PORT", "8080"),
            database_path=Path(values.get("DATABASE_PATH", "/data/bridge.db")),
            git_dir=Path(values.get("GIT_DIR", "/data/repository.git")),
            ssh_key=Path(values.get("GITHUB_SSH_KEY", "/run/secrets/github_deploy_key")),
            known_hosts=Path(values.get("GITHUB_KNOWN_HOSTS", "/run/secrets/known_hosts")),
        )

    @property
    def repository_ssh(self) -> str:
        return f"git@github.com:{self.repository}.git"

    @property
    def repository_web(self) -> str:
        return f"https://github.com/{self.repository}"
